apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: openshift-mcp-server-release-040-stage
  namespace: ocp-mcp-server-tenant
  labels:
    release.appstudio.openshift.io/automated: "false"
    release.appstudio.openshift.io/author: kpande
spec:
  releasePlan: openshift-mcp-server-releaseplan-040-stage
  snapshot: openshift-mcp-server-040-override-snapshot-1
  data:
    releaseNotes:
      references:
        - "https://github.com/openshift/openshift-mcp-server/blob/release-0.4/docs/openshift/user-guide.md"
      type: "RHEA"
