apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: openshift-mcp-server-release-020-prod
  namespace: ocp-mcp-server-tenant
  labels:
    release.appstudio.openshift.io/automated: "false"
    release.appstudio.openshift.io/author: kpande
spec:
  releasePlan: openshift-mcp-server-releaseplan-020-prod
  snapshot: openshift-mcp-server-020-override-snapshot-4
  data:
    releaseNotes:
      references:
        - "https://github.com/openshift/openshift-mcp-server/blob/release-0.2.0/docs/openshift/user-guide.md"
      type: "RHEA"
