apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-mcp-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- regexReplaceAll "(?m)(= -?\\d+)\\.0$" (tpl (toToml .Values.config) .) "${1}" | nindent 4 }}
