apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
      version: blue
  template:
    metadata:
      labels:
        app: checkout-service
        version: blue
    spec:
      containers:
      - name: app
        image: nginxinc/nginx-unprivileged:1.28
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: nginx-cache
          mountPath: /var/cache/nginx
        ports:
        - containerPort: 8080
      volumes:
      - name: tmp
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
