kind: Task
metadata:
  labels:
    suite: core
    project: kubernetes
  annotations:
    project-name: "Kubernetes"
    project-url: "https://kubernetes.io"
  name: debug-app-logs
  difficulty: medium
steps:
  setup:
    file: setup.sh
  prompt:
    inline: "What wrong with my calc-app-pod in the calc-app namespace?"
  cleanup:
    file: cleanup.sh
  verify:
    contains: "division by zero"
