apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: openshift-mcp-server-020-override-snapshot-4
  namespace: ocp-mcp-server-tenant
  labels:
    test.appstudio.openshift.io/type: override
    application: mcp-server-02
    branch: release-0.2.0
spec:
  application: mcp-server-02
  components:
    - name: openshift-mcp-server-release-020
      # Use the digest from a successful Konflux build, not a mutable tag.
      containerImage: "quay.io/redhat-user-workloads/ocp-mcp-server-tenant/openshift-mcp-server-release-020@sha256:731ac2b3e19fad64296125ae91dbd83dcde8661846e03cefaead76dce7ff2918"
      source:
        git:
          url: "https://github.com/openshift/openshift-mcp-server"
          revision: "46e2b48f00d2747be6ed4c4d79f530cd5c80b8b4"
          dockerfileUrl: "Dockerfile.ocp"
