apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: openshift-mcp-server-releaseplan-100-stage
  namespace: ocp-mcp-server-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "false"
    release.appstudio.openshift.io/releasePlanAdmission: openshift-mcp-server-100-stage
    release.appstudio.openshift.io/standing-attribution: "true"
spec:
  application: mcp-server-10
  target: rhtap-releng-tenant
  data:
    releaseNotes:
      solution: |
        The Model Context Protocol server for Red Hat OpenShift helps manage MCP workloads on OpenShift.
      description: "The 1.0 release of Model Context Protocol server for Red Hat OpenShift."
      topic: |
        The 1.0 release of Model Context Protocol server for Red Hat OpenShift. This release introduces MCP server capabilities on OpenShift.
      synopsis: "Model Context Protocol server for Red Hat OpenShift 1.0"
