kind: Task
metadata:
  labels:
    suite: core
    project: kubernetes
  annotations:
    project-name: "Kubernetes"
    project-url: "https://kubernetes.io"
  name: setup-dev-cluster
  difficulty: hard
steps:
  setup:
    file: setup.sh
  verify:
    file: verify.sh
  cleanup:
    file: cleanup.sh
  prompt:
    file: setup-dev-cluster.md
