require_oauth = true
oauth_audience = "mcp-server"
oauth_scopes = ["openid", "mcp-server"]
validate_token = false
authorization_url = "https://keycloak.keycloak.svc:8443/realms/openshift"
sts_client_id = "mcp-server"
sts_client_secret = "mcp-server-dev-secret"
sts_audience = "openshift"
sts_scopes = ["mcp:openshift"]
certificate_authority = "_output/cert-manager-ca/ca.crt"
